 version: "3"

services:
  mjpg-streamer:
    build:
      context: ./mjpg-streamer
      dockerfile: Dockerfile
    restart: always
    privileged: true
    ports:
      - 8080:8080
    environment:
      - INPUT_FLAGS=-r 1640x1232 -f 10
      - OUTPUT_FLAGS=-w ./www
    volumes:
      - /run/udev:/run/udev:ro

  octoprint:
    image: octoprint/octoprint:latest
    restart: always
    privileged: true
    ports:
      - 9001:80
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - /opt/Octoprint/data/octoprint:/octoprint
      - /proc/cpuinfo:/proc/cpuinfo:ro
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd:ro
      - /usr/lib/aarch64-linux-gnu/libvcos.so.0:/usr/lib/aarch64-linux-gnu/libvcos.so.0:ro
      - /usr/lib/aarch64-linux-gnu/libvchiq_arm.so.0:/usr/lib/aarch64-linux-gnu/libvchiq_arm.so.0:ro
